server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth_service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/auth/**
              filters:
                - StripPrefix=2

            - id: user_service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/user/**
              filters:
                - StripPrefix=2

            - id: project_service
              uri: http://localhost:8083
              predicates:
                - Path=${app.api-prefix}/project/**
              filters:
                - StripPrefix=2

            - id: chat_service
              uri: http://localhost:8084
              predicates:
                - Path=${app.api-prefix}/chat/**
              filters:
                - StripPrefix=2