spring:
  application:
    name: projectService

  datasource:
    url: jdbc:mysql://localhost:3306/project
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: project-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8083
  servlet:
    context-path: /project

app:
  services:
    profile: http://localhost:8082/user